name: Daily Commit

on:
  schedule:
    - cron: "0 6 * * *"   # tous les jours 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update daily.md
        run: |
          echo "Update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> daily.md

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily update [skip ci]"
          file_pattern: daily.md
          commit_user_name: "mcieric"
          commit_user_email: "mcieric13@gmail.com"
          branch: main
          push_options: '--force-with-lease'
