name: Multi-Repo Daily Build Log

on:
  schedule:
    - cron: "0 5 * * *"     # 05:00 UTC chaque jour
  workflow_dispatch:

permissions:
  contents: read   # le push se fait via ton PAT (secret)

concurrency:
  group: multi-daily-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: [
          "mcieric/zen-erc20",
          "mcieric/zen-daily"
          # ajoute d'autres repos ici si tu veux
        ]
        branch: ["main"]

    steps:
      - name: Clone target repo ${{ matrix.repo }}
        run: |
          git clone https://x-access-token:${{ secrets.MULTI_REPO_TOKEN }}@github.com/${{ matrix.repo }}.git target

      - name: Append line & push (with rebase + retries)
        run: |
          set -e
          cd target
          git config user.name "mcieric"
          git config user.email "mcieric13@gmail.com"

          mkdir -p logs
          test -f logs/build-log.md || echo "# Build log" > logs/build-log.md

          for i in 1 2 3; do
            echo "Attempt $i on ${{ matrix.repo }}"
            git fetch origin
            git checkout ${{ matrix.branch }}
            git pull --rebase --autostash origin ${{ matrix.branch }} || true

            echo "Build log $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> logs/build-log.md
            git add logs/build-log.md
            git commit -m "chore: daily build log [skip ci]" || echo "no changes"

            if git push --force-with-lease origin ${{ matrix.branch }}; then
              echo "Push OK for ${{ matrix.repo }}"
              break
            fi

            echo "Push rejected; retrying in $((i*5))s…"
            sleep $((i * 5))
          done
